const Map<String, String> resCode = {
  "1000": "OK",
  "9992": "Bài viết không tồn tại",
  "9993": "Mã xác thực không đúng",
  "9994": "Không có dữ liệu hoặc không còn dữ liệu",
  "9995": "Không có người dùng này",
  "9996": "Người dùng đã tồn tại",
  "9997": "Phương thức không đúng",
  "9998": "Sai token",
  "9999": "Lỗi exception",
  "1001": "Lỗi kết nối CSDL",
  "1002": "Số lượng tham số không đầy đủ",
  "1003": "Kiểu tham số không hợp lệ",
  "1004": "Giá trị tham số không hợp lệ",
  "1005": "Lỗi không xác định",
  "1006": "Kích cỡ file vượt ngưỡng cho phép",
  "1007": "Tải file thất bại",
  "1008": "Số lượng hình ảnh vượt mức quy định",
  "1009": "Không có quyền truy cập tài nguyên",
  "1010": "Hành động đã được người dùng thực hiện trước đây",
  "1011": "Bài đăng vi phạm tiêu chuẩn cộng đồng",
  "1012": "Bài đăng bị giới hạn ở một số quốc gia",
  "9991": "Tài khoản hoặc mật khẩu không chính xác",
  "9990": "Mật khẩu không chính xác",
  "5001": "Lỗi cơ sở dữ liệu"
};
